package jcalculador;

/**
 * @author KevinPC
 */

public class VentanaData extends javax.swing.JFrame {
    
    private Archivos bitacora;
    private String path;
    
    public VentanaData(Archivos p, String path) {
        initComponents();
        setLocationRelativeTo(this);
        this.bitacora = p;
        this.path = path;
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlArchivos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaBitacora = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlArchivos.setBackground(new java.awt.Color(51, 51, 51));
        pnlArchivos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlArchivos.setForeground(new java.awt.Color(255, 255, 255));

        txaBitacora.setBackground(new java.awt.Color(51, 51, 51));
        txaBitacora.setColumns(20);
        txaBitacora.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txaBitacora.setForeground(new java.awt.Color(255, 255, 255));
        txaBitacora.setRows(5);
        txaBitacora.setEnabled(false);
        jScrollPane1.setViewportView(txaBitacora);

        javax.swing.GroupLayout pnlArchivosLayout = new javax.swing.GroupLayout(pnlArchivos);
        pnlArchivos.setLayout(pnlArchivosLayout);
        pnlArchivosLayout.setHorizontalGroup(
            pnlArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArchivosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlArchivosLayout.setVerticalGroup(
            pnlArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArchivosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlArchivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlArchivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrar(){
        txaBitacora.setText(bitacora.readFile(path));
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlArchivos;
    private javax.swing.JTextArea txaBitacora;
    // End of variables declaration//GEN-END:variables
}
